/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Static export: every page is pre-rendered to `out/` and served by
  // Cloudflare as static assets, with no Worker code running per request.
  // Redirects live in public/_redirects (generated by scripts/redirects.mjs)
  // because Next's redirects() doesn't run in a static export.
  output: 'export',
  trailingSlash: false,
};

export default nextConfig;
